
public class About extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    public About() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btBack = new javax.swing.JButton();
        lblAbout = new javax.swing.JLabel();
        lblbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(760, 760));
        setMinimumSize(new java.awt.Dimension(760, 760));
        setResizable(false);
        getContentPane().setLayout(null);

        btBack.setFont(new java.awt.Font("A little sunshine", 1, 48)); // NOI18N
        btBack.setForeground(new java.awt.Color(0, 153, 51));
        btBack.setText("BACK");
        btBack.setBorderPainted(false);
        btBack.setContentAreaFilled(false);
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        getContentPane().add(btBack);
        btBack.setBounds(280, 50, 210, 70);

        lblAbout.setFont(new java.awt.Font("A little sunshine", 1, 18)); // NOI18N
        lblAbout.setForeground(new java.awt.Color(204, 204, 204));
        lblAbout.setText("<html> <head>     <title></title> </head>  <body>     <h1>Description -</h1>      <p>This game is played on a vertical board which has seven hollow columns and seven rows. Each column has a hole in the upper part of the board, where pieces are introduced.<br>     In short, it´s a vertical board with 49 windows distributed in 7 rows and 7 columns. Both players have total 49 thin pieces (like coins); each of them uses a different colour. The board is empty at the start of the game.</p>      <h1>Objective -</h1>      <p>The aim for both players is to make a straight line of four own pieces; the line can be vertical, horizontal or diagonal.</p>      <h1>How the game goes on -</h1>      <p>Before starting, players decide randomly which of them will be the beginner; moves are made alternatively, one by turn.<br>     Moves entails in placing new pieces on the board; pieces slide downwards from upper holes, falling down to the last row or piling up on the last piece introduced in the same column. So, in every turn the introduced piece may be placed at most on seven different squares.<br>     The winner is the first player who gets a straight line made with four own pieces and no gaps between them.</p>     </body> </html> ");
        getContentPane().add(lblAbout);
        lblAbout.setBounds(80, 210, 620, 420);

        lblbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        getContentPane().add(lblbg);
        lblbg.setBounds(0, -20, 760, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        new Splash().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblbg;
    // End of variables declaration//GEN-END:variables
}
