
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Splash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmdset = new javax.swing.JButton();
        cmdexit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("PWScratchedfont", 0, 78)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("CONNECT 4");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        cmdset.setBackground(new java.awt.Color(204, 204, 204));
        cmdset.setFont(new java.awt.Font("A little sunshine", 1, 48)); // NOI18N
        cmdset.setForeground(new java.awt.Color(0, 153, 51));
        cmdset.setText("Help");
        cmdset.setBorderPainted(false);
        cmdset.setContentAreaFilled(false);
        cmdset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsetActionPerformed(evt);
            }
        });
        getContentPane().add(cmdset, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 160, 80));

        cmdexit.setBackground(new java.awt.Color(204, 204, 204));
        cmdexit.setFont(new java.awt.Font("A little sunshine", 1, 48)); // NOI18N
        cmdexit.setForeground(new java.awt.Color(0, 153, 51));
        cmdexit.setText("Exit");
        cmdexit.setBorderPainted(false);
        cmdexit.setContentAreaFilled(false);
        cmdexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdexitActionPerformed(evt);
            }
        });
        getContentPane().add(cmdexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 150, 80));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("A little sunshine", 1, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 51));
        jButton1.setText("Play");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 150, 80));

        lblBg.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        lblBg.setForeground(new java.awt.Color(153, 102, 0));
        lblBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        lblBg.setText("CONNECT 4");
        lblBg.setMaximumSize(new java.awt.Dimension(760, 760));
        lblBg.setMinimumSize(new java.awt.Dimension(760, 740));
        getContentPane().add(lblBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsetActionPerformed
        new About().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdsetActionPerformed

    private void cmdexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cmdexitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new VS_Player().setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Splash().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdexit;
    private javax.swing.JButton cmdset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBg;
    // End of variables declaration//GEN-END:variables
}
