
import classes.pclass;
import javax.swing.JOptionPane;


public class VS_Player extends javax.swing.JFrame {

    /**
     * Creates new form VS_Player
     */
    
    public VS_Player() {
        initComponents();
        //Constructor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Player1BG = new javax.swing.ButtonGroup();
        Player2BG = new javax.swing.ButtonGroup();
        Player3BG = new javax.swing.ButtonGroup();
        Player4BG = new javax.swing.ButtonGroup();
        Player5BG = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        redp1 = new javax.swing.JRadioButton();
        txtp1 = new javax.swing.JTextField();
        txtp2 = new javax.swing.JTextField();
        redp2 = new javax.swing.JRadioButton();
        bluep1 = new javax.swing.JRadioButton();
        bluep2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(760, 760));
        setMinimumSize(new java.awt.Dimension(760, 760));
        setPreferredSize(new java.awt.Dimension(731, 647));
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(204, 0, 51));
        jLabel2.setFont(new java.awt.Font("A little sunshine", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Player 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 290, 80, 30);

        jLabel4.setFont(new java.awt.Font("A little sunshine", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("Player 2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 350, 100, 30);

        Player1BG.add(redp1);
        redp1.setFont(new java.awt.Font("A little sunshine", 1, 18)); // NOI18N
        redp1.setForeground(new java.awt.Color(255, 102, 102));
        redp1.setText("Red");
        redp1.setContentAreaFilled(false);
        getContentPane().add(redp1);
        redp1.setBounds(510, 290, 70, 27);

        txtp1.setBackground(new java.awt.Color(204, 204, 204));
        txtp1.setFont(new java.awt.Font("A little sunshine", 1, 18)); // NOI18N
        txtp1.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(txtp1);
        txtp1.setBounds(280, 290, 190, 31);

        txtp2.setBackground(new java.awt.Color(204, 204, 204));
        txtp2.setFont(new java.awt.Font("A little sunshine", 1, 18)); // NOI18N
        txtp2.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(txtp2);
        txtp2.setBounds(280, 350, 190, 31);

        Player2BG.add(redp2);
        redp2.setFont(new java.awt.Font("A little sunshine", 1, 18)); // NOI18N
        redp2.setForeground(new java.awt.Color(255, 102, 102));
        redp2.setText("Red");
        redp2.setContentAreaFilled(false);
        getContentPane().add(redp2);
        redp2.setBounds(510, 350, 60, 27);

        Player1BG.add(bluep1);
        bluep1.setFont(new java.awt.Font("A little sunshine", 1, 18)); // NOI18N
        bluep1.setForeground(new java.awt.Color(0, 153, 255));
        bluep1.setText("Blue");
        bluep1.setContentAreaFilled(false);
        getContentPane().add(bluep1);
        bluep1.setBounds(600, 290, 60, 30);

        Player2BG.add(bluep2);
        bluep2.setFont(new java.awt.Font("A little sunshine", 1, 18)); // NOI18N
        bluep2.setForeground(new java.awt.Color(0, 153, 255));
        bluep2.setText("Blue");
        bluep2.setContentAreaFilled(false);
        getContentPane().add(bluep2);
        bluep2.setBounds(600, 350, 90, 27);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("A little sunshine", 1, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 51));
        jButton1.setText("Back");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 50, 190, 60);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("A little sunshine", 1, 48)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 51));
        jButton2.setText("Submit");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 510, 190, 70);

        bg.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 760, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Splash().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String p1 = txtp1.getText();
        String p2 = txtp2.getText();
        if(redp1.isSelected()){
            if(redp2.isSelected()){
                JOptionPane.showMessageDialog(null, "Only one red allowed.");
                Player1BG.clearSelection();
                Player2BG.clearSelection();
            }
        }
        else if(redp2.isSelected()){
            if(redp1.isSelected()){
                JOptionPane.showMessageDialog(null, "Only one red allowed.");
                Player1BG.clearSelection();
                Player2BG.clearSelection();
            }
        }
        if(bluep1.isSelected()){
            if(bluep2.isSelected()){
                JOptionPane.showMessageDialog(null, "Only one blue allowed.");
                Player1BG.clearSelection();
                Player2BG.clearSelection();
            }
        }
        else if(bluep2.isSelected()){
            if(bluep1.isSelected()){
                JOptionPane.showMessageDialog(null, "Only one blue allowed.");
                Player1BG.clearSelection();
                Player2BG.clearSelection();
            }
        }
        
        if("".equals(p1) || "".equals(p2)){
            JOptionPane.showMessageDialog(null, "Please enter names for players.");
        }
    
        
        if(bluep1.isSelected() && redp2.isSelected()){
            pclass.p1c = "blue";
            pclass.p2c = "red";
        }
        else if(bluep2.isSelected() && redp1.isSelected()){
            pclass.p2c = "blue";
            pclass.p1c = "red";
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select player colour.");
        }
        pclass.p1 = p1;
        pclass.p2 = p2;
        
        if(!"".equals(p1) && !"".equals(p2) && pclass.p1 != "" && pclass.p2 != "" && pclass.p1c != "" && pclass.p2c != ""){
        new Play().setVisible(true);
        this.dispose();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VS_Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VS_Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VS_Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VS_Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VS_Player().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Player1BG;
    private javax.swing.ButtonGroup Player2BG;
    private javax.swing.ButtonGroup Player3BG;
    private javax.swing.ButtonGroup Player4BG;
    private javax.swing.ButtonGroup Player5BG;
    private javax.swing.JLabel bg;
    private javax.swing.JRadioButton bluep1;
    private javax.swing.JRadioButton bluep2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton redp1;
    private javax.swing.JRadioButton redp2;
    private javax.swing.JTextField txtp1;
    private javax.swing.JTextField txtp2;
    // End of variables declaration//GEN-END:variables
}
